// MIT License - Copyright (c) fintonlabs.com
import type { CaptureMeta, RawEvent } from '../../../shared/types'

/**
 * Coordinate spaces used throughout the engine:
 *
 *  - **source**  capture pixels (e.g. 2880x1800). Input events live here.
 *  - **output**  export pixels (e.g. 1920x1080). The final frame.
 *  - **content** the rect inside `output` that the screen video occupies once
 *                background padding has been subtracted.
 *
 * The camera maps a *viewport* rect in source space onto the content rect.
 */

export interface Vec2 {
  x: number
  y: number
}

export interface Rect {
  x: number
  y: number
  w: number
  h: number
}

// ---------------------------------------------------------------------------
// Background & frame
// ---------------------------------------------------------------------------

export type BackgroundKind = 'gradient' | 'solid' | 'mesh' | 'image' | 'none'

export interface Background {
  kind: BackgroundKind
  /** Gradient / mesh stops. Solid uses the first entry. */
  colors: string[]
  angle: number
  /** Blurred, scaled copy of the recording behind the frame. */
  useWallpaperBlur?: boolean
  imageSrc?: string
  /** 0..1 fraction of the shorter output edge added as noise/grain. */
  grain: number
}

export interface FrameStyle {
  /** Padding as a fraction of the shorter output edge, 0..0.28. */
  padding: number
  /** Corner radius in output pixels at 1080p, scaled with output size. */
  radius: number
  shadow: {
    blur: number
    opacity: number
    y: number
    spread: number
  }
  border: {
    width: number
    color: string
  }
  /** Rotation in degrees; small values only, keeps pixels square-ish. */
  rotate: number
  /** 'contain' letterboxes the source, 'cover' crops it (vertical exports). */
  fitMode: 'contain' | 'cover'
}

// ---------------------------------------------------------------------------
// Zoom
// ---------------------------------------------------------------------------

export interface ZoomSegment {
  id: string
  /** Seconds, on the recording timeline. */
  start: number
  end: number
  /** Ramp durations in seconds. */
  easeIn: number
  easeOut: number
  /** Magnification relative to the fully-zoomed-out framing. */
  scale: number
  /** Anchor point in source pixels. */
  x: number
  y: number
  /** True when generated by the auto-zoom pass rather than the user. */
  auto: boolean
  /** How strongly the camera tracks the cursor inside this segment, 0..1. */
  follow: number
  locked?: boolean
}

export interface ZoomSettings {
  enabled: boolean
  /** Upper bound on generated magnification. */
  maxScale: number
  minScale: number
  /** Seconds of lead-in before the triggering action. */
  lead: number
  /** Seconds the zoom holds after the last action in a cluster. */
  hold: number
  /** Clusters closer than this merge into one segment. */
  mergeGap: number
  easeIn: number
  easeOut: number
  /** Camera tracking of the cursor while zoomed, 0..1. */
  follow: number
  /** Which signals generate zooms. */
  triggers: {
    clicks: boolean
    scrolls: boolean
    keys: boolean
    appSwitches: boolean
    dwell: boolean
  }
  /** Extra temporal smoothing of camera motion, in seconds. */
  smoothing: number
}

// ---------------------------------------------------------------------------
// Cursor
// ---------------------------------------------------------------------------

export interface CursorSettings {
  visible: boolean
  /** 1 = true recorded size at output scale. */
  size: number
  /** 0 = raw recorded path, 1 = heavily smoothed glide. */
  smoothing: number
  /** Pull the pointer back onto the true position around clicks. */
  clickAnchoring: boolean
  /** Fade the pointer out after this many idle seconds; 0 disables. */
  idleHide: number
  /** Ease the pointer back to its opening position at the end of the take. */
  returnToStart: boolean
  clicks: {
    enabled: boolean
    /** Expanding ring on click. */
    ring: boolean
    color: string
    /** Radius in output pixels at 1080p. */
    radius: number
    duration: number
    /** Pointer squash on press. */
    press: boolean
  }
  /** Dim everything except a radial pool around the pointer. */
  spotlight: {
    enabled: boolean
    radius: number
    dim: number
  }
}

// ---------------------------------------------------------------------------
// Camera picture-in-picture
// ---------------------------------------------------------------------------

export interface PipSettings {
  enabled: boolean
  shape: 'circle' | 'rounded' | 'square'
  /** Size as a fraction of output height. */
  size: number
  position: 'bottom-left' | 'bottom-right' | 'top-left' | 'top-right' | 'custom'
  /** Used when position is 'custom'; fraction of output size. */
  customX: number
  customY: number
  /** Inset from the output edge, fraction of output height. */
  margin: number
  mirror: boolean
  radius: number
  border: { width: number; color: string }
  shadow: { blur: number; opacity: number; y: number }
  /** Shrink and fade the bubble when the pointer gets close to it. */
  avoidCursor: boolean
  /** Zoom applied inside the bubble, for framing the face. */
  zoom: number
  offsetX: number
  offsetY: number
}

// ---------------------------------------------------------------------------
// Timeline
// ---------------------------------------------------------------------------

export interface TimelineClip {
  /** Source-time bounds of the retained region, in seconds. */
  start: number
  end: number
  /** Playback rate; >1 speeds the region up. */
  speed: number
}

export interface KeystrokeSettings {
  enabled: boolean
  position: 'bottom' | 'top'
  duration: number
}

export interface Project {
  output: { width: number; height: number; fps: number }
  background: Background
  frame: FrameStyle
  zoom: ZoomSettings
  segments: ZoomSegment[]
  cursor: CursorSettings
  pip: PipSettings
  keystrokes: KeystrokeSettings
  clips: TimelineClip[]
  audio: { systemGain: number; micGain: number }
}

// ---------------------------------------------------------------------------
// Parsed recording
// ---------------------------------------------------------------------------

export interface ClickEvent {
  t: number
  x: number
  y: number
  button: number
  count: number
}

export interface ScrollEvent {
  t: number
  x: number
  y: number
  dx: number
  dy: number
}

export interface KeyEvent {
  t: number
  chars: string
  mods: string[]
}

export interface AppEvent {
  t: number
  app: string
  rect?: Rect
}

export interface CursorShapeEvent {
  t: number
  name: string
}

export interface ParsedInput {
  moves: { t: number; x: number; y: number }[]
  clicks: ClickEvent[]
  presses: { t: number; down: boolean; button: number }[]
  scrolls: ScrollEvent[]
  keys: KeyEvent[]
  apps: AppEvent[]
  shapes: CursorShapeEvent[]
}

export interface Recording {
  dir: string
  meta: CaptureMeta
  raw: RawEvent[]
  input: ParsedInput
  screenURL: string
  cameraURL?: string
  /** Camera start, in seconds on the recording timeline. */
  cameraOffset: number
  duration: number
  source: { width: number; height: number }
}
